### ISSUE TITLE
EpubByteContentFileRef.readContent() to return Future<Uint8List>

### ISSUE THREAD

**Issue by lastant** [orthros/dart-epub#32]
With an older version of flutter 0.5.1 and epub 1.3.2 I could load an image in a the Image widget with `EpubByteContentFileRef.readContent()` and `Image.memory(...)`. But with the latest flutter dev version 0.5.8 and epub 2.0.2 there is an exception: `type 'List<int>' is not a subtype of type 'Uint8List'`

**Comment by orthros** [comment]
Can you give a more detailed description? Full disclosure: it has been a long time since I have worked with flutter.

It sounds like you are trying to something like

``` dart
EpubBook epubRef = await EpubReader.readBook(bytes);
Image img = Image.memory(epubRef.CoverImage.getBytes());
```
Is that correct?

**Comment by lastant** [comment]
No, the CoverImage has class Image from the dart image package.
I want to display images from the content: `epubRef.Content.Images[imgHref].readContent()`

**Comment by lastant** [comment]
The current workaround for me is to use `Uint8List.fromList()`, but it apparently copies the original array, which apparently copies the array and might be slow for big images.

**Comment by lastant** [comment]
https://github.com/brendan-duncan/archive/issues/55#issuecomment-418233496

**Comment by orthros** [comment]
I recommend looking at the example in the `examples/flutter_ex` folder. This shows how to get the image rendered in a Flutter application
