### ISSUE TITLE
Failed decoding image

### ISSUE THREAD

**Issue by AndreHaueisen** [orthros/dart-epub#34]
@orthros I'm trying to do exactly [that](https://github.com/orthros/dart-epub/issues/32#issuecomment-414158692), but I'm getting a decoding error. Can you point me in the right direction?

```
E/flutter (17553): [ERROR:flutter/lib/ui/painting/codec.cc(100)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter (17553): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (17553): The following _Exception was thrown resolving an image codec:
I/flutter (17553): Exception: operation failed
```

**Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!

**Comment by orthros** [comment]
I recommend looking in the `example/flutter_ex` folder for an example of how to use this library to display cover images in a Flutter application
