### ISSUE TITLE
About the file size

### ISSUE THREAD

**Issue by arkanmgerges** [orthros/dart-epub#37]
Hi, and thanks for sharing this dart package. Just a question, did you test it on files that have sizes > 2 mega bytes ?

I'm asking because if this is a memory friendly when the file size is big, maybe the app will crash.

Thanks

**Comment by ShadowJonathan** [comment]
Side note: in my experience, when you have a +2MB file, you either have a ridicilously big book (4M words), or a few dozen big images sprinkled in.

**Comment by arkanmgerges** [comment]
Ok, so you are saying that this is rarely for us to find epub with file size > 2 mega bytes.
Ok, thanks for this information
