### ISSUE TITLE
Package epub has no versions that match >=1.2.0 <2.0.0

### ISSUE THREAD

**Issue by jmgeffroy** [orthros/dart-epub#4]
Hi,
I'm trying to play with this package but until now I get the following error when doing `flutter packages get`:
```
Package epub has no versions that match >=1.2.0 <2.0.0 derived from:
- EpubTestApp depends on version ^1.2.0
```
Any idea? Thanks a lot in advance!

**Comment by orthros** [comment]
Thanks for reporting!  I'll have to take a look at that. Can you reproduce in a dart-only environment (i.e. no flutter involved)? 

Right now by using
Dart Version
```
Using this pubspec.yaml 
```
name: dartProjTmp
version: 1.0.0
author: Colin Nelson <colin@orthros.co>
description: Test Package
environment:
  sdk: ">=1.21.0 <2.0.0"
dependencies:
  epub: ^1.2.0
dev_dependencies:  
```

**Comment by orthros** [comment]
So I can confirm I can replicate this issue, but I also notice that when running 
```
flutter --version
```

from an out of the box `flutter` install I get the following

```
C:\Dev\tmp\test_proj> flutter --version
Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (3 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```
The last line: `Dart 2.0.0-dev` makes me think that this is why `pub `can't resolve the package as the `pubspec.yaml` for this project explicitly states < 2.0.0

Can you confirm you are getting similar output from `flutter --version`?

Thanks!

**Comment by orthros** [comment]
Last follow up for now: I've installed the dart beta version (2.0.0)
```
C:\Dev\Personal\dart-epub [master ≡ +1 ~0 -0 !]> dart --version
Dart VM version: 2.0.0-dev.35.0 (Fri Mar 9 13:09:14 2018 +0100) on "windows_x64"
```
And after a `pub get` I can confirm that my unit tests pass.

I don't want to prematurely release the package, but if you can confirm that the `dart` version you are using with `flutter` is ~2.0.0 I'll test further and update the version. Otherwise, I'll start down other diagnostic routes.

Thanks!

**Comment by jmgeffroy** [comment]
Hi ! 
Sorry for the late reply, I'm located in France... And thanks a lot for your ultra-fast replies.
Yes I confirm I'm getting the exact same info with `flutter --version`:
```
Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (3 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```
Best regards

**Comment by orthros** [comment]
No need to apologize. We are from all over around here!

With the latest merge to master #12 this should work.

Using this pubspec.yaml
```
name: test_proj
description: A new Flutter project.
dependencies:
  flutter:
    sdk: flutter
  epub:  ^1.2.8
  cupertino_icons: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```
And running `flutter packages pub get` successfully imported the package.
 
Can you confirm it is resolved for you too?
Thanks!

**Comment by jmgeffroy** [comment]
Hi, 
Thank you so much, it works !
Fantastic, eager to further test...
Very best regards,

**Comment by orthros** [comment]
Glad to hear! I'll close this. Please let me know if you encounter any other issues 👍
