### ISSUE TITLE
dart-epub needs to be updated to support the latest flutter_test

### ISSUE THREAD

**Issue by Miki-AG** [orthros/dart-epub#41]
See error below:

Because every version of flutter_test from sdk depends on async 2.1.0 and epub >=1.3.0 depends on async >=1.8.0 <2.1.0, flutter_test from sdk is incompatible with epub >=1.3.0.

**Comment by Miki-AG** [comment]
As a workaround, you can override async:

dependency_overrides:
  async: 2.0.0

**Comment by novrian6** [comment]
Yes please to  support latest flutter test.
Because every version of flutter_test from sdk depends on async 2.1.0 and epub >=1.3.0 depends on async >=1.8.0 <2.1.0, flutter_test from sdk is incompatible with epub >=1.3.0.

using dependency overrides, does not work as well now.

**Comment by orthros** [comment]
Thanks for surfacing this. This should be closed with PR #42

**Comment by orthros** [comment]
Please feel free to open a new issue if this persists, but PR #42 should close this
