### ISSUE TITLE
Any chance of making a Flutter Widget view of these epubs?

### ISSUE THREAD

**Issue by bolasim** [orthros/dart-epub#65]
There doesn't seem to be an epub renderer out there. Is this something you've thought about or would like help doing?

**Comment by orthros** [comment]
Thanks for the suggestion! 

I've considered making a renderer several times (and if you go through the examples directory in this repo you can see I started experimenting a little while ago), but I've always fallen short of "diving in".

I'm be interested in doing so, but a full renderer is probably beyond what I could put out as a single person working on the project at this precise moment in time. I've seen some good examples in other languages (JavaScript etc.) that would make a good starting point for a renderer in Flutter, but I'd need to investigate further.
